[versions]
# libraries
annotations = "26.0.2"
kotlinxSerialization = "1.8.1"
junit = "4.13.2"
lsp4j = "0.21.1"

# plugins
changelog = "2.2.1"
intelliJPlatForm = "2.5.0"
kotlin = "2.1.0"
kover = "0.9.1"

[libraries.lsp4j]
group = "org.eclipse.lsp4j"
name = "org.eclipse.lsp4j"
version.ref = "lsp4j"

[libraries.lsp4jdebug]
group = "org.eclipse.lsp4j"
name = "org.eclipse.lsp4j.debug"
version.ref = "lsp4j"

[libraries.annotations]
group = "org.jetbrains"
name = "annotations"
version.ref = "annotations"

[libraries.kotlinxSerialization]
group = "org.jetbrains.kotlinx"
name = "kotlinx-serialization-json"
version.ref = "kotlinxSerialization"

[libraries.junit]
group = "junit"
name = "junit"
version.ref = "junit"

[plugins.changelog]
id = "org.jetbrains.changelog"
version.ref = "changelog"

[plugins.intelliJPlatForm]
id = "org.jetbrains.intellij.platform"
version.ref = "intelliJPlatForm"

[plugins.kotlin]
id = "org.jetbrains.kotlin.jvm"
version.ref = "kotlin"

[plugins.kover]
id = "org.jetbrains.kotlinx.kover"
version.ref = "kover"

[plugins.kotlinSerialization]
id = "org.jetbrains.kotlin.plugin.serialization"
version.ref = "kotlin"
